apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "rental-prediction-isvc"
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://sigma-bucket-us-east-2/rental-prediction-model/"  
